import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { adminUpdateOrder, createOrder, fetchAllOrders } from "./orderAPI";

const initialState = {
  orders: [],
  status: "idle",
  orderPlaced: null,
  totalCount: 0,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const createOrderAsync = createAsyncThunk(
  "orders/createOrder",
  async (orderData) => {
    const response = await createOrder(orderData);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchAllOrdersAsync = createAsyncThunk(
  "orders/fetchAllOrders",
  async (pagination) => {
    const response = await fetchAllOrders(pagination);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

//update order
export const adminUpdateOrderAsync = createAsyncThunk(
  "orders/adminUpdateOrder",
  async (order) => {
    const response = await adminUpdateOrder(order);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const orderSlice = createSlice({
  name: "order", //reducer name
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    //action for resetting the current orders
    resetOrder: (state) => {
      state.orderPlaced = null;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(createOrderAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(createOrderAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.orders.push(action.payload);
        state.orderPlaced = action.payload;
      })
      .addCase(fetchAllOrdersAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchAllOrdersAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.orders = action.payload.orders;
        state.totalCount = action.payload.totalOrders;
      })
      .addCase(adminUpdateOrderAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(adminUpdateOrderAsync.fulfilled, (state, action) => {
        state.status = "idle";
        const index = state.orders.findIndex(
          (order) => order.id === action.payload.id
        );
        state.orders[index] = action.payload;
      });
  },
});

export const { resetOrder } = orderSlice.actions; //exporting the resetOrder action

export const selectCurrentOrder = (state) => state.order.orderPlaced;

export const selectAllOrders = (state) => state.order.orders;
export const selectTotalOrders = (state) => state.order.totalCount;

export default orderSlice.reducer;
